ALTER TABLE reports
  ADD COLUMN IF NOT EXISTS ai_generated boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS ai_metadata jsonb,
  ADD COLUMN IF NOT EXISTS reviewed_at timestamptz,
  ADD COLUMN IF NOT EXISTS reviewed_by uuid REFERENCES auth.users ON DELETE SET NULL;

COMMENT ON COLUMN reports.ai_generated IS 'True when this report was generated by an AI model';
COMMENT ON COLUMN reports.ai_metadata IS '{"model": str, "version": str, "prompt_hash": str, "temperature": float, "generated_at": iso8601}';
COMMENT ON COLUMN reports.reviewed_at IS 'Timestamp when a therapist validated this AI-generated report';
COMMENT ON COLUMN reports.reviewed_by IS 'User who validated the AI content (EU AI Act Art. 50 human oversight)';
